# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 958ba98b8ec98b5345b1419e9b45157b2ab3e5773d16d9630264a02b9bd02cb13f3d9da67809f8f09c72d82445daba8431a7e05b98e5d5f400e14c497c2ba006

test:
  secret_key_base: 04196282244f4c5eb0adafe5742210f2daaff71e1889c2c73bba51f2f5c62aee559a48757716394697264eada636dc8bf9fcd27e72f0a2e847cc81373aed25aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
